---
sidebar: sidebar
permalink: create-workspaces.html
keywords: manage, workspace, snapshot, project 
summary: A workspace in NetApp Workload Factory for EDA is a Perforce representation of a project that is based off of a project snapshot. You can create workspaces as part of an EDA project.
---
= Create an EDA workspace
:icons: font
:imagesdir: ./media/

[.lead]
A workspace in NetApp Workload Factory for EDA is a Perforce representation of a project at a specific moment in time. Workspaces are created using a project snapshot as a basis. You can create new workspaces within an EDA project. You can create workspaces from the Perforce UI.

//== Create a workspace
//You can create a new workspace from a snapshot of a project.

.Before you begin
Ensure you have integrated EDA with the Perforce Helix Visual Client. See link:integrate-perforce.html[Integrate EDA with Perforce^] for more information.

.Steps
. Log in to Perforce.
. In the Perforce menu, select *View* > *WF*.
+
The Workload Factory login screen appears within the Perforce UI.
. Log in to Workload Factory using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Builders workloads tile, select *Create project*.
. Select *Create workspace*. 
. On the Create a workspace project page, provide the following:
.. Select a snapshot to use as a basis for the workspace.
.. Enter a name for the workspace.
.. Optionally, enter a user identifier to claim the workspace. This identifier should match the Perforce user ID of the developer that will use this workspace.
. Select *Create*.

.Result
The workspace is created, and appears in the list of workspaces on the Workspaces page.


