---
sidebar: sidebar
permalink: learn-builders.html
keywords: software builders, development, benefits
summary: Workload Factory for Builders is a rapid build environment creation tool for software builders. 
---
= Learn about Workload Factory for Builders
:icons: font
:imagesdir: ./media/

[.lead]
Workload Factory for Builders is a rapid build environment creation tool for software builders. It enables rapid setup of personal development environments, saving time and enabling self-service for developers while empowering DevOps teams to retain control of the infrastructure. Using Builders, software developers can quickly create workspaces without needing specialized data storage or understanding of the development infrastructure.

== What is Workload Factory for Builders?
Workload Factory for Builders enables the rapid creation of software development environments and uses Amazon FSx for NetApp ONTAP filesystems to store them. Perforce integration enables version control and efficient storage of large artifacts on the filesystem. The data protection and snapshot capabilities of Amazon FSx for NetApp ONTAP enable developers to quickly switch between projects or versions of a project without having to rebuild their environment.

For more information about Workload Factory, refer to the link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html[Workload Factory overview^].

=== Operational modes in Workload Factory
Three different operational modes - _basic_, _read_ and _automate_ - offer flexible options for deployment inside and outside of Workload Factory. Gain immediate value at zero-trust in _basic_ mode with code snippets for use outside Workload Factory. Get incremental value with incremental trust in _read_ and _automate_ modes. 

Learn more about link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html[operational modes in Workload Factory^].

== Workload Factory for Builders features
Workload Factory for Builders offers the following features:

*
*
*
*
*
*
*
*

== Project management with Builders
Information about using projects in Builders goes here.

== Automation with Workload Factory Codebox
Workload Factory introduces built-in automation with the _Codebox_. The Codebox offers the following automation benefits: 

* *Code snippet generation*: Infrastructure-as-Code (IaC) snippets are generated during resource creation, allowing seamless integration with existing orchestration workflows. 
* *Infrastructure-as-code co-pilot*: the Codebox is an Infrastructure-as-code (IaC) co-pilot that helps developers and DevOps generate code to execute any operation supported by Workload Factory.  
* *Code viewer and automation catalog*: the Codebox provides a code viewer for quick analysis of automation and an automation catalog for quick future re-use. 

== Benefits of using Builders to create build environments
Here are some benefits of using Builders to speed up and simplify your organization's creation and management of build environments:

*
*
*

== Cost
There is no cost for using the Builders capability of Workload Factory.

== Licensing
No special licenses are needed from NetApp to use the Builders capabilities of Workload Factory.

=== Integrated AWS services
Builders includes the following integrated AWS services: 

* CloudFormation
* Simple Notification Service 
* CloudWatch
* Systems Manager
* Secrets Manager 

=== Supported regions
Databases is supported in all commercial regions where FSx for ONTAP is supported. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/[View supported Amazon regions.^]

The following AWS regions aren't supported: 

* China regions
* GovCloud (US) regions
* Secret Cloud
* Top Secret Cloud

== Getting help
Amazon FSx for NetApp ONTAP is an AWS first-party solution. For questions or technical support issues associated with your FSx for ONTAP file system, infrastructure, or any solution using this service, use the Support Center in your AWS Management Console to open a support case with AWS. Select the “FSx for ONTAP” service and appropriate category. Provide the remaining information required to create your AWS support case.

For general questions about Workload Factory or Workload Factory applications and services, refer to link:get-help-databases.html[Get help for Databases for Workload Factory].