---
sidebar: sidebar
permalink: learn-builders.html
keywords: software builders, development, benefits
summary: Workload factory for Builders is a rapid build environment creation tool for software builders. 
---
= Learn about workload factory for Builders
:icons: font
:imagesdir: ./media/

[.lead]
Workload factory for Builders is a rapid build environment creation tool for software builders. It enables fast setup of personal development environments, saving time and enabling self-service for developers while empowering DevOps teams to retain control of the infrastructure. Using Builders, software developers can quickly create workspaces without needing specialized data storage or understanding of the development infrastructure.

== What is workload factory for Builders?
Workload factory for Builders enables the rapid creation of software development environments and uses Amazon FSx for NetApp ONTAP filesystems to store them. Perforce integration enables version control and efficient storage of large artifacts on the filesystem. The data protection and snapshot capabilities of Amazon FSx for NetApp ONTAP enable developers to quickly switch between projects or versions of a project without having to rebuild their environment.

Workload factory for Builders leverages ONTAP's snapshot and clone features with version control systems like Perforce to provide a managed and monitored service. This enables engineering teams to quickly access different versions without syncing with the version control system, significantly speeding up development, QA, CI/CD, and verification processes, and reducing time to market.

For more information about workload factory, refer to the link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html[workload factory overview^].

== Workload factory for Builders features
Workload factory for Builders offers the following features:

* Integrate with version control systems such as Perforce
* Create clones of workspaces
* Create snapshots of projects
* Create, edit, and remove projects and workspaces
* Associate FSx filesystems with each project
* Create access policies to control who has access to a project
* Analyze capacity usage of each project
* Create operation policies to control clone size limits and clone retention

== Projects and workspaces in Builders
When you use Builders, you create a project to represent your build environment and its artifacts. Each project can contain one or more workspaces. Each workspace is a point in time snapshot of the build environment (for example, a different version of the software, or another instance of the same version). You can quickly switch between workspaces if you need to work on a different version, test experimental changes, or update a previous release.

== Operational modes in workload factory
Three different operational modes - _basic_, _read_ and _automate_ - offer flexible options for deployment inside and outside of workload factory. Gain immediate value at zero-trust in _basic_ mode with code snippets for use outside workload factory. Get incremental value with incremental trust in _read_ and _automate_ modes. 

Learn more about link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html[operational modes in workload factory^].

== Automation with workload factory Codebox
Workload factory introduces built-in automation with the _Codebox_. The Codebox offers the following automation benefits: 

* *Code snippet generation*: Infrastructure-as-Code (IaC) snippets are generated during resource creation, enabling seamless integration with existing orchestration workflows. 
* *Infrastructure-as-code co-pilot*: the Codebox is an Infrastructure-as-code (IaC) co-pilot that helps developers and DevOps generate code to execute any operation supported by workload factory.  
* *Code viewer and automation catalog*: the Codebox provides a code viewer for quick analysis of automation and an automation catalog for quick future re-use. 

== Cost
There is no cost for using the Builders capability of workload factory.

== Licensing
No special licenses are needed from NetApp to use the Builders capabilities of workload factory.

//=== Integrated AWS services
//Builders includes the following integrated AWS services: 

=== Supported regions
Builders is supported in all commercial regions where FSx for ONTAP is supported. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/[View supported Amazon regions.^]

The following AWS regions aren't supported: 

* China regions
* GovCloud (US) regions
* Secret Cloud
* Top Secret Cloud

== Getting help
Amazon FSx for NetApp ONTAP is an AWS first-party solution. For questions or technical support issues associated with your FSx for ONTAP file system, infrastructure, or any solution using this service, use the Support Center in your AWS Management Console to open a support case with AWS. Select the “FSx for ONTAP” service and appropriate category. Provide the remaining information required to create your AWS support case.

For general questions about workload factory or workload factory applications and services, refer to link:get-help-builders.html[Get help for Builders for workload factory].