---
sidebar: sidebar
permalink: learn-eda.html
keywords: software builders, development, benefits, eda, electronic design automation
summary: NetApp Workload Factory for EDA helps you optimize FSx for ONTAP usage performance. 
---
= Learn about NetApp Workload Factory for EDA
:icons: font
:imagesdir: ./media/

[.lead]

Workload Factory for EDA helps you optimize FSx for ONTAP across multiple file system to boost performance and reduce operational costs through automated storage parameter management. It integrates with your existing Infrastructure as Code (IaC), ensuring consistent and reliable use by workloads.

Workload Factory for EDA provides dashboard and storage automation frameworks and utilities that help you manage multiple FSx for ONTAP file systems. 

It offers the following: 

* link:task-configure-dashboard.html[The project dashboard]: provides a centralized view of storage consumption across your FSx for ONTAP file systems to help you plan, assess costs, and collect information on storage usage across your projects.
* link:learn-eda-workloads.html[CI/CD]: streamlines and reduces software build time by leveraging FSx for ONTAP volume clone capabilities. 