---
sidebar: sidebar
permalink: manage-project.html
keywords: Microsoft SQL Server instance, server instance, manage host, view host, database host, database instance, manage, unmanage
summary: Manage Microsoft SQL Server instances in workload factory for Databases. 
---
= Manage Builders projects
:icons: font
:imagesdir: ./media/

[.lead]
You can manage Builders projects to control how your code and artifacts are managed for each project in workload factory for Builders. 

== View projects
You can view existing projects created in workload factory for Builders by following these steps. 

.Steps
. Log in to workload factory using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Builders tile, select *Go to Projects page*. 
+
View the existing projects listed on the Projects page.

== Edit a project
You can edit the settings of a project at any time. 

.Steps
. Log in to workload factory using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Builders tile, select *Go to Projects page*. 
. On the Projects page, select the actions menu for the project you want to edit.
. Make any needed changes to the project configuration.
. Select *Save*.

== Create a snapshot of a project
// How do you view snapshots?
You can create a snapshot of a project by following these steps.

.Steps
. Log in to workload factory using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Builders tile, select *Go to Projects page*. 
. On the Projects page, select the actions menu for the project you want to snapshot.
. In the resulting menu, select *Create a snapshot*.
. In the *Create snapshot* dialog, choose a name for the snapshot and select *Create*.

////
== Clone a project 
You can view the databases managed by the managed instance by following these steps. 

.Steps
. Log in to workload factory using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Builders tile, select *Create project*. 
. On the Create project page, provide the following:
.. *Project name*: Enter a name for the project.
////

== Create a clone of a project
You can use the workload factory API to create a clone of a project.


== View a project's workspaces
A clone or snapshot of a project is known as a workspace. When you create a workspace, it is retained for as long as the project's operation policy allows. You can view existing workspaces for a project by following these steps.

.Steps
. Log in to workload factory using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Builders tile, select *Go to Projects page*. 
. On the Projects page, choose a project and select *View*.
. View the status and details of all workspaces for this project.
. If you see alerts or warnings for a workspace, hover over the alert or warning icon to see the reason.

== Delete a project
You can delete a project when it is no longer needed by following these steps.

.Steps
. Log in to workload factory using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Builders tile, select *Go to Projects page*. 
. On the Projects page, select the actions menu for the project you want to delete.
. Select *Delete*.
. In the confirmation dialog, select *Delete*.

.Result
The project is deleted, and any code or artifacts associated with the project are deleted from the volume. Snapshots and clones of the project are retained.


