settings:
  name: "Builders workloads"
  platform: cloud
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  release_notes_autogen:
    release_notes_repo: workload-relnotes  

sidebar: 
  entries:
  - title: Builders workloads docs
    url: /index.html
  - title: Release notes  
    entries:
      - title: What's new
        url: /whats-new.html
      - title: Known limitations
        url: /known-limitations.html 
  - title: Get started
    entries: 
      - title: Learn about Workload Factory for Builders
        url: /learn-builders.html 
      - title: Quick start
        url: /quick-start-builders.html
      - title: Requirements
        url: /requirements-builders.html 
  - title: Use Builders workloads
    entries: 
      - title: Create a project
        url: /create-project.html 
      - title: Automate with Codebox
        url: /automate-codebox.html
  - title: Use Perforce
    entries: 
      - title: Integrate Builders with Perforce
        url: /integrate-perforce.html 
      - title: Manage Perforce 
        url: /manage-perforce.html
  - title: Administer and monitor
    entries:
      - title: Manage projects
        url: /manage-projects.html
      - title: Manage workspaces
        url: /manage-projects.html
      - title: Monitor projects
        url: /monitor-projects.html                                
  - title: Knowledge and support
    entries: 
      - title: Register for support
        url: /support-registration-databases.html
      - title: Get help
        url: /get-help-databases.html                  
  - title: Legal notices
    url: /legal-notices.html

product-family:
  name: BlueXP Workload Factory for AWS
  repo: workload-family
