settings:
  name: "EDA workloads" 
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  release_notes_autogen:
    release_notes_repo: workload-relnotes  

sidebar: 
  entries:
  - title: EDA workloads docs
    url: /index.html
  - title: Release notes  
    entries:
      - title: What's new
        url: /whats-new.html
      - title: Known limitations
        url: /known-limitations.html 
  - title: Get started
    entries: 
      - title: Learn about NetApp Workload Factory for EDA
        url: /learn-eda.html 
      - title: Quick start
        url: /quick-start-eda.html
  - title: Use the project dashboard
    entries: 
      - title: Use the dashboard
        url: /task-configure-dashboard.html
  - title: Use Perforce integration
    entries: 
      - title: Learn about Perforce integration
        url: /learn-eda-workloads.html
      - title: Requirements
        url: /requirements-eda.html 
      - title: Manage projects
        url: /manage-projects.html
      - title: Manage project versions
        url: /version-projects.html
      - title: Create a workspace
        url: /create-workspaces.html
      - title: Automate with Codebox
        url: /automate-codebox.html
      - title: Integrate with Perforce
        url: /integrate-perforce.html
  # - title: Use Perforce
  #   entries: 
  #     - title: Integrate EDA with Perforce
  #       url: /integrate-perforce.html 
  #     - title: Manage Perforce 
  #       url: /manage-perforce.html
  #- title: Administer and monitor projects
  #  entries:
  #    - title: Create a project
  #      url: /create-projects.html
  #    - title: Manage workspaces
  #      url: /manage-projects.html
  #    - title: Monitor projects
  #      url: /monitor-projects.html
  #    - title: Clone a project
  #      url: /create-project-clone.html
  #    - title: Create a snapshot of a project
  #      url: /create-project-snapshot.html
  - title: Knowledge and support
    entries: 
      - title: Register for support
        url: /support-registration.html
      - title: Get help
        url: /get-help-eda.html                  
  - title: Legal notices
    url: /legal-notices.html

product-family:
  name: NetApp Workload Factory
  repo: workload-family
